{
 "title": "Orchestrator status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Orch status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(orchestrator_errors_count_total{}[1h])*3600",
     "legendFormat": "ERRORS COUNT"
    },
    {
     "expr": "rate(orchestrator_warnings_count_total{}[1h])*3600",
     "legendFormat": "WARNINGS COUNT"
    },
    {
     "expr": "rate(orchestrator_errors_count_cosmos_eth{}[1h])*3600",
     "legendFormat": "COSMOS ETH"
    },
    {
     "expr": "rate(orchestrator_warnings_count_eth{warn_message=\"Could not contact Eth node\"}[1h])*3600",
     "legendFormat": "ETH WARNS"
    }
   ]
  },
  {
   "title": "last checked event nonce",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"last_checked_event\"}"
    }
   ]
  },
  {
   "title": "latest gravity height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"latest_cosmos_block\"}"
    }
   ]
  },
  {
   "title": "Latest ETH height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"latest_eth_block\"}"
    }
   ]
  }
 ]
}